package com.neuedu.dao;

import com.neuedu.pojo.Order;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int insert(@Param("order")Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    Order selectByPrimaryKey(@Param("id")Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    List<Order> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(@Param("order")Order record);

    /**
     * 按照userid查找
     */
    List<Order>findOrderListByUserId(@Param("userId")Integer userId);

    /**
     * 按照userid和订单号查找
     */
    Order findOrderListByUserIdAndOrderNO(@Param("userId")Integer userId,@Param("orderNO")Long orderNO);

    /**
     * 按照订单号模糊查找
     */
    List<Order>findOrderListByOrderNO(@Param("orderNO")String orderNO);

    /**
     * 更新发货时间
     */
    int updateSend(@Param("order")Order record);

    /**
     * 更新支付时间
     */
    int updatePay(@Param("order")Order record);

    /**
     * 更新关闭时间
     */
    int updateClose(@Param("order")Order record);

    /**
     * 查询需要关闭的订单
     */
    List<Order> selectOrdersByCreateTime(@Param("time")String time);
}